item1 = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(item1))
print ('É um número?',item1.isnumeric())
print('é alfabético?', item1.isalpha())
print('É alfanumérico?', item1.isalnum())
print('É só espaços?',item1.isspace())
print('Está em maiúsculas?', item1.isupper())
print('Está em minúsculo?',item1.islower())
print('Está capitalizada?', item1.istitle())
